sudo: false
language: c
compiler: gcc
env:
  matrix: 
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc6-dev-i386
      - linux-libc-dev
      - gcc-multilib
      - libx11-dev
      - libx11-dev:i386
      - git
      - subversion
      - automake
      - libtool
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libboost-all-dev
      - libgoogle-perftools-dev
      - libxmlrpc-c++.*-dev
      - cmake
      - csh
      - libX11-dev
script:
- ./bjam -j4
- find . | grep bin
- du -sh

